name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  ci_branching:
    uses: tinybirdco/ci/.github/workflows/ci_branching.yml@v1.0.0
    with:
      tb_host: https://api.tinybird.co
    secrets: 
      admin_token: ${{ secrets.ADMIN_TOKEN }}
