name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize]
    paths-ignore:
      - '.github/**'

env:
  ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  TB_HOST: https://api.tinybird.co
  
jobs:
  create_workspace:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Set environment variables
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Install Tinybird CLI
        run: pip install tinybird-cli

      - name: Tinybird version
        run: tb --version       

      - name: Check all the data files syntax
        run: tb check  

      - name: Create new branch workspace with data
        run: |
          tb \
          --host $TB_HOST \
          --token $ADMIN_TOKEN \
          branch create tmp_ci_${GITHUB_RUN_ID} \
          --last-partition --wait

      - name: List changes with main branch
        run: tb diff --main --no-verbose

      - name: Push changes to the branch workspace
        run: |
          PUSH_FILE=./deployment/${{env.GIT_BRANCH}}-push.sh
          if [ -f "$PUSH_FILE" ]; then
            ./deployment/${{env.GIT_BRANCH}}-push.sh
          else
            ./deployment/default-push.sh
          fi

      - name: List changes with branch (should be empty)
        run: tb diff

      - name: Run data quality tests
        run: |
          tb test run -v

      - name: Get regression labels
        id: regression_labels
        uses: SamirMarin/get-labels-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_key: regression

      - name: Run pipe regression tests
        run: |
          REGRESSION_FILE=./deployment/${{env.GIT_BRANCH}}-regression.yaml
          echo ${{ steps.regression_labels.outputs.labels }}
          if [ -f "$REGRESSION_FILE" ]; then
            tb branch regression-tests -f ./deployment/${{env.GIT_BRANCH}}-regression.yaml --wait
          else
            tb branch regression-tests coverage .* --wait ${{ steps.regression_labels.outputs.labels }}
          fi


  cleanup:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [create_workspace]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install Tinybird CLI
        run: pip install tinybird-cli

      - name: Tinybird version
        run: tb --version       

      - name: Drop CI branch workspace
        run: |
          tb \
          --host $TB_HOST \
          --token $ADMIN_TOKEN \
          branch rm tmp_ci_${GITHUB_RUN_ID} \
          --yes